---
title             : "A Time-varying Computational Model of Learning to Read Printed Words Aloud"
shorttitle        : "A Time-varying Model of Reading Aloud"

#author:  
#  - name          : "Matt Cooper Borkenhagen"
#    affiliation   : "1"
#    corresponding : yes
#    email         : "cooperborken@wisc.edu"
#    address       : "1202 West Johnson Street, Madison, WI 53705"

#affiliation:
#  - id            : "1"
#    institution   : "Department of Psychology, University of Wisconsin, Madison"

#abstract: |
#  A computational model of word naming (pronunciation) is described.
  
#keywords          : "reading, language development"
#wordcount         : "XXX"
bibliography      : ["references.bib"]
documentclass     : "apa6"
#class             : "man"
figsintext        : yes
figurelist        : no
tablelist         : yes
footnotelist      : no
lineno            : no
lang              : "en-US"
output            :
  papaja::apa6_pdf :
    toc               : true
    toc_depth         : 3

header-includes:
  - \geometry{left=3cm, right=3cm, top=3cm, bottom=3cm}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \PassOptionsToPackage{x11names}{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
  - \usepackage{pdfpages}
  - \interfootnotelinepenalty=10000
  - \setcounter{page}{0}
  #- \usepackage{fancyhdr}
  #- \fancyhead[R]{\thepage}
  #- \usepackage{setspace}
  #- \captionsetup[figure]{font={stretch=2, scriptsize}}
  #- \usepackage{tikz}
---

```{r global_options, include = FALSE, eval = F, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      cache = FALSE,
                      echo = FALSE,
                      out.extra = "",
                      fig.pos = "t!",  sanitize = TRUE)
options(knitr.table.format = "latex")
options(knitr.kable.NA = '')
options(scipen = 1000)
#knitr::knit_hooks$set(inline = function(x) {if(!is.numeric(x)){x}else{prettyNum(round(x,2), big.mark=",")}})
#knit_hooks$set(inline = function(x) {prettyNum(x, big.mark=",")})
```


```{r loads, echo=FALSE, warning=FALSE, include=FALSE}

# requirements
packages = read.csv('requirements.txt', stringsAsFactors = F)[[1]]
lapply(packages, require, ch = T)

source('scripts/utilities.R')
# we reference some ch3 data here in chapter 2 so we will compile all data here
# note that source scripts are in ./data/
source('scripts/data.R')
```

```{r child='1_chapter.Rmd'}
```

```{r child='2_chapter.Rmd'}
```

```{r child='3_chapter.Rmd'}
```

```{r child='4_chapter.Rmd'}
```
# References


