---
title             : ""
shorttitle        : ""
output            :
  papaja::apa6_pdf :
    toc               : false
header-includes:
  - \setcounter{page}{1}
  - \setlength\parindent{12pt}
  - \pagestyle{plain}
  - \usepackage{setspace}
  - \pagenumbering{roman}
---
\thispagestyle{empty}
\newpage

\begin{center}
\thispagestyle{empty}
\vspace{5cm}
A Time-varying Computational Model of Learning to Read Printed Words Aloud \\
\vfil
by \\  
Matthew James Cooper Borkenhagen \\
\vfil
A dissertation submitted in partial fulfillment of \\
the requirements for the degree of \\
Doctor of Philosophy \\
(Psychology) \\
\vfil
at the \\
\textsc{University of Wisconsin - Madison} \\
2022 \\
\vfil

\vfil
\end{center}
\begin{singlespace}
\noindent Date of final oral examination: To be determined \newline
Members of the Final Oral Committee: \newline
\indent Mark S. Seidenberg, Professor, Psychology \newline
\indent Martha Alibali, Professor, Psychology \newline
\indent Maryellen MacDonald, Professor, Psychology \newline
\indent Robert Nowak, Professor, Electrical and Computer Engineering \newline
\indent Timothy T. Rogers, Professor, Psychology
\end{singlespace} 
\clearpage

\newpage
