---
title: "introduction"
output: html_document
---

# Chapter 1: Introduction

## Overview
Words are read by virtue of perceptual and cognitive processes that are distributed across space and time. As a reader engages visually with a word printed on the page, the reader's eyes move by fixation in semi-systematic ways across portions of printed word, tapping her or his knowledge of speech, print, and meaning. Historically, cognitive accounts of word reading have been focused on the simplest of words of English - those with one syllable (perry2010, rastle2000jml, sibley2010, yap2009), especially in the connectionist learning literature (plaut1996, seidenberg1989, sibley2010). This focus results from two primary factors. First, any model of word reading must at the very least account for the development of knowledge of the simplest words in the language given the child develops the ability to read these words first (ref.). Second, accounting for words that are longer than one syllable requires the specification of a learning architecture that accounts for time-varying aspects of learning that must be happening over longer words. This includes but is not limited to variability in prosodic information involved in pronunciation over different syllables (especially of vowels and their associated patterns of stress).

This dissertation reports on a model of word reading (that associates print to speech) that can accommodate words that are not bounded by orthographic or phonological length - that is, of words that are not limited to a single syllable. This is a significant advance from previous models in that the types of words it can recognize (printed and spoken) resemble those that are naturalistic in terms of the word environments that children (and adults) learn within.

The remaining chapters of this dissertation are organized in the following way. First, in the remaining portion of Chapter 1, I will introduce the central issues in word reading as they relate to the type of sequential processing that is essential to the theory developed in the dissertation. In Chapter 2, a history of models of word recognition will be provided. Chapter 3 will develop the architecture and corresponding theory of naming that represents the core topic of the dissertation. Chapter 4 will provide several experiments using the architecture described in Chapter 3, forming the behavioral support validating the architecture. Chapter 5 will be the conclusion, which will discuss the theory in light of its limitations and future directions.

# Introduction
Language comes and goes in a time-contingent fashion. The language that we see and hear is structured by sequential statistics that are processed through processes that happen across time. Among other important perceptual and cognitive aspects of language processing, letters are processed visually according to patterns of fixation that occur in a temporally governed manner, auditory processes take place relative to sound patterns that appear in a fast fading way over time. As a result, our theoretical models should account for the fact that such processing takes place in a sequentially arranged, time-contingent manner. This is especially true of reading given that the activity involves several such processes, each of which is distributed across time.

Prevailing models of word reading have dealt with temporal aspects of processing in three ways: (1) through the use of networks that have a continuous recurrent component to their architecture (harm1999, harm2004), (2) implicit implementations with the use of feedforward networks that possess a component of the architecture dedicated to stress (perry2010), or (3) using simple recurrent networks (sibley2010). How time factors into word reading is typically discussed in the literature as concerning the processing of syllables: models of word reading can either deal with polysyllabic words or not. This distinction makes sense at one level, given that syllables are an important unit of speech. They carry information about vowel stress, and are an organizational category of language, contributing to the understanding of how consonants and vowels cluster within and across words. However, sequential statistics relevant to long words go beyond structure related to syllables. For example, orthotactic patterns exist as a matter of linguistic structure not strictly tied to syllabic structure.

In a separate research tradition, several architectures have been proposed in the engineering literature in order to simulate the relationship between text and speech for technological and commercial ends.



