---
title             : "A time-varying computational model of naming"
shorttitle        : ""

author:  
  - name          : "Matt Cooper Borkenhagen"
    email         : "cooperborken@wisc.edu"
    address       : "1202 West Johnson Street, Madison, WI 53705"

affiliation:
  - id            : "1"
    institution   : "Department of Psychology, University of Wisconsin, Madison"

keywords          : "reading, language development"
wordcount         : "XXX"
documentclass     : "apa6"
lang              : "en-US"
output            :
  papaja::apa6_pdf :
    toc               : false
header-includes:
#  - \PassOptionsToPackage{x11names}{xcolor}
#  - \usepackage{wrapfig}
#  - \usepackage{float}
#  - \usepackage{colortbl}
#  - \usepackage{pdflscape}
#  - \usepackage{tabu}
#  - \usepackage{threeparttable}
#  - \usepackage[normalem]{ulem}
#  - \usepackage{pdfpages}
#  - \interfootnotelinepenalty=10000
  - \setcounter{page}{1}
  - \setlength\parindent{24pt}
  - \pagestyle{plain}
---
\thispagestyle{empty}
\newpage

\begin{center}
\vspace*{\stretch{1}}
\thispagestyle{empty}
Your text centered
\vspace*{\stretch{1}}
\end{center}



\newpage


# Committee Members
Committee Chair: Mark S. Seidenberg, Ph.D. \newline
\indent \indent Vilas and Donald O. Hebb Professor, Department of Psychology \newline
\indent \indent University of Wisconsin - Madison \newline

Committee Member: Martha Alibali, Ph.D. \newline
\indent \indent Professor, Department of Psychology \newline
\indent \indent University of Wisconsin - Madison \newline

Committee Member: Maryellen MacDonald, Ph.D. \newline
\indent \indent Donald P. Hayes Professor, Department of Psychology \newline
\indent \indent University of Wisconsin - Madison \newline

Committee Member: Robert D. Nowak, Ph.D. \newline
\indent \indent Nosbusch Professor, Departments of Electrical and Computer Engineering \newline
\indent \indent University of Wisconsin - Madison \newline

Committee Member: Timothy T. Rogers, Ph.D. \newline
\indent \indent Professor, Department of Psychology \newline
\indent \indent University of Wisconsin - Madison \newline
\newpage

# Acknowledgements